version: '3'
services:
    psdk-docker:
        build: 
            context: .
            args:
                RUBY_VERSION: 2.6.6
        stdin_open: true
        tty: true
        container_name: psdk-docker
        entrypoint: /entrypoint.sh
        environment: 
            - DISPLAY=:2
        ports:
            - "127.0.0.1:5902:5900"
        volumes:
            - ..:/psdk/litergss
            - ../external/litecgss:/psdk/litecgss
            - ../external/SFML:/psdk/SFML
            - ../external/ruby:/root/.rake-compiler/ruby
