version: '3'
services:
    psdk-host-tools:
        build:
            context: host-tools
        entrypoint: /entrypoint.sh
        env_file: 
            - mingw.env
        volumes: 
            - ../../generated:/target/mingw
    ruby:
        build:
            context: ruby
            args:
                RUBY_VERSION: 2.6.6
        environment: 
            CLEAN_BUILD: "n"
        entrypoint: /entrypoint.sh
        depends_on:
            - psdk-host-tools
        volumes:
            - ../../generated/ruby:/target/ruby
            - ruby-compiler-volume:/usr/src/ruby/target
    sfml:
        build:
            context: sfml
        entrypoint: /entrypoint.sh
        depends_on:
            - psdk-host-tools
        volumes:
            - sfml-compiler-volume:/SFML
            - ../../generated:/target/SFML
    litecgss:
        build:
            context: litecgss
        entrypoint: /entrypoint.sh
        environment: 
            CLEAN_BUILD: "n"
        depends_on:
            - sfml
        volumes:
            - ../../external/litecgss:/source/litecgss
            - ../../generated:/target/litecgss
            - sfml-compiler-volume:/tmp-SFML
    rubyfmod:
        build:
            context: rubyfmod
            args:
                RUBY_VERSION: 2.6.6
        entrypoint: /entrypoint.sh
        environment: 
            CLEAN_BUILD: "n"
        depends_on:
            - ruby
        volumes:
            - ../../generated:/target/rubyfmod
    litergss:
        build: 
            context: litergss
            args:
                RUBY_VERSION: 2.6.6
        environment: 
            CLEAN_BUILD: "n"
        entrypoint: /entrypoint.sh
        depends_on:
            - ruby
            - litecgss
        volumes:
            - ../..:/source/litergss
            - ../../external/litecgss:/source/litecgss
            - ruby-compiler-volume:/source/ruby
            - sfml-compiler-volume:/tmp-SFML
            - ../../generated:/target/litergss
            
volumes:
    sfml-compiler-volume:
    ruby-compiler-volume:
